export const news = [
  {
    id: "a1b2",
    title: "Tech Innovations",
    text: "Exciting developments in the tech world as new innovations promise to reshape industries.",
    image: "https://picsum.photos/800/400?random=1",
    date: "2023-09-29",
    writer: "John Doe",
    view_count: 1200,
    category: "Technology",
  },
  {
    id: "c3d4",
    title: "Healthy Living",
    text: "Discover the latest trends in healthy living and wellness to improve your lifestyle.",
    image: "https://picsum.photos/800/400?random=2",
    date: "2023-09-28",
    writer: "Jane Smith",
    view_count: 850,
    category: "Health",
  },
  {
    id: "e5f6",
    title: "Space Exploration",
    text: "Astronomers make groundbreaking discoveries as space exploration reaches new heights.",
    image: "https://picsum.photos/800/400?random=3",
    date: "2023-09-27",
    writer: "Alan Johnson",
    view_count: 1500,
    category: "Science",
  },
  {
    id: "g7h8",
    title: "Culinary Delights",
    text: "Explore the world of exquisite flavors and culinary delights from around the globe.",
    image: "https://picsum.photos/800/400?random=4",
    date: "2023-09-26",
    writer: "Samantha Turner",
    view_count: 1100,
    category: "Technology",
  },
  {
    id: "i9j0",
    title: "Artistic Expressions",
    text: "Immerse yourself in the beauty of artistic expressions as talented creators showcase their work.",
    image: "https://picsum.photos/800/400?random=5",
    date: "2023-09-25",
    writer: "David Rodriguez",
    view_count: 980,
    category: "Art",
  },
  {
    id: "k1l2",
    title: "Financial Insights",
    text: "Stay informed about the latest trends and insights in the world of finance and investments.",
    image: "https://picsum.photos/800/400?random=6",
    date: "2023-09-24",
    writer: "Emily White",
    view_count: 1300,
    category: "Science",
  },
  {
    id: "m3n4",
    title: "Nature's Wonders",
    text: "Witness the wonders of nature with breathtaking landscapes and wildlife photography.",
    image: "https://picsum.photos/800/400?random=7",
    date: "2023-09-23",
    writer: "Michael Brown",
    view_count: 1050,
    category: "Health",
  },
  {
    id: "o5p6",
    title: "Fashion Trends",
    text: "Explore the latest fashion trends and styles that are making waves in the industry.",
    image: "https://picsum.photos/800/400?random=8",
    date: "2023-09-22",
    writer: "Olivia Miller",
    view_count: 1150,
    category: "Art",
  },
  {
    id: "q7r8",
    title: "Gaming Universe",
    text: "Dive into the gaming universe with reviews, previews, and exciting updates from the gaming world.",
    image: "https://picsum.photos/800/400?random=9",
    date: "2023-09-21",
    writer: "Ryan Clark",
    view_count: 1400,
    category: "Technology",
  },
  {
    id: "s9t0",
    title: "Travel Adventures",
    text: "Embark on virtual travel adventures with captivating stories and stunning imagery from around the world.",
    image: "https://picsum.photos/800/400?random=10",
    date: "2023-09-20",
    writer: "Sophia Turner",
    view_count: 1250,
    category: "Health",
  },
];
