export const products = [
  {
    id: 1,
    name: "iPhone 13 Pro Max",
    image:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-iphone-13-pro-max-silver-2023?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1679072987085",
    description: "The latest iPhone model with advanced features.",
    price: 799.99,
    category: "Electronics",
    brand: "Apple",
    rating: 3.0,
    in_stock: true,
    color: "Midnight Green",
    weight: "0.2 kg",
    dimensions: {
      length: "5.78 inches",
      width: "2.82 inches",
      height: "0.30 inches",
    },
  },
  {
    id: 2,
    name: "MacBook Air",
    image: "https://picsum.photos/800/600",
    description: "A sleek and lightweight laptop for productivity.",
    price: 1199.99,
    category: "Electronics",
    brand: "Apple",
    rating: 4.9,
    in_stock: true,
    color: "Silver",
    weight: "1.29 kg",
    dimensions: {
      length: "11.97 inches",
      width: "8.36 inches",
      height: "0.63 inches",
    },
  },
  {
    id: 3,
    name: "Samsung 4K Smart TV",
    image: "https://picsum.photos/800/600",
    description: "Experience stunning visuals with this 4K Smart TV.",
    price: 899.99,
    category: "Electronics",
    brand: "Samsung",
    rating: 4.7,
    in_stock: true,
    color: "Black",
    weight: "18.2 kg",
    dimensions: {
      length: "48.4 inches",
      width: "9.9 inches",
      height: "30.4 inches",
    },
  },
  {
    id: 4,
    name: "Levi's Men's Jeans",
    image: "https://picsum.photos/800/600",
    description: "Classic and comfortable jeans for men.",
    price: 59.99,
    category: "Clothing",
    brand: "Levi's",
    rating: 4.6,
    in_stock: true,
    color: "Blue",
    weight: "0.8 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 5,
    name: "KitchenAid Stand Mixer",
    image: "https://picsum.photos/800/600",
    description: "A versatile kitchen gadget for baking enthusiasts.",
    price: 299.99,
    category: "Kitchen",
    brand: "KitchenAid",
    rating: 4.9,
    in_stock: true,
    color: "Empire Red",
    weight: "11.3 kg",
    dimensions: {
      length: "14.1 inches",
      width: "8.7 inches",
      height: "13.9 inches",
    },
  },
  {
    id: 6,
    name: "Sony Noise-Canceling Headphones",
    image: "https://picsum.photos/800/600",
    description:
      "Immerse yourself in high-quality audio with noise-canceling technology.",
    price: 249.99,
    category: "Electronics",
    brand: "Sony",
    rating: 4.5,
    in_stock: true,
    color: "Black",
    weight: "0.24 kg",
    dimensions: {
      length: "7.31 inches",
      width: "2.94 inches",
      height: "9.93 inches",
    },
  },
  {
    id: 7,
    name: "Adidas Running Shoes",
    image: "https://picsum.photos/800/600",
    description: "Comfortable and durable running shoes for athletes.",
    price: 79.99,
    category: "Footwear",
    brand: "Adidas",
    rating: 4.7,
    in_stock: true,
    color: "White/Blue",
    weight: "0.4 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 8,
    name: "LG UltraWide Monitor",
    image: "https://picsum.photos/800/600",
    description: "A wide and immersive monitor for productivity and gaming.",
    price: 499.99,
    category: "Electronics",
    brand: "LG",
    rating: 4.8,
    in_stock: true,
    color: "Black",
    weight: "7.5 kg",
    dimensions: {
      length: "44.4 inches",
      width: "9.1 inches",
      height: "21.5 inches",
    },
  },
  {
    id: 9,
    name: "Nike Air Max Sneakers",
    image: "https://picsum.photos/800/600",
    description: "Stylish and comfortable sneakers for everyday wear.",
    price: 129.99,
    category: "Footwear",
    brand: "Nike",
    rating: 4.6,
    in_stock: true,
    color: "Black/Red",
    weight: "0.5 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 10,
    name: "Bose SoundLink Speaker",
    image: "https://picsum.photos/800/600",
    description: "Portable Bluetooth speaker with rich sound quality.",
    price: 129.99,
    category: "Electronics",
    brand: "Bose",
    rating: 4.7,
    in_stock: true,
    color: "Silver",
    weight: "0.67 kg",
    dimensions: {
      length: "2.24 inches",
      width: "5.16 inches",
      height: "5.00 inches",
    },
  },
  {
    id: 11,
    name: "Sony 65-Inch 4K OLED TV",
    image: "https://picsum.photos/800/600",
    description: "Experience breathtaking visuals with this 4K OLED TV.",
    price: 1999.99,
    category: "Electronics",
    brand: "Sony",
    rating: 4.9,
    in_stock: true,
    color: "Black",
    weight: "24.7 kg",
    dimensions: {
      length: "57.0 inches",
      width: "13.9 inches",
      height: "35.0 inches",
    },
  },
  {
    id: 12,
    name: "Calvin Klein Men's Dress Shirt",
    image: "https://picsum.photos/800/600",
    description: "A stylish dress shirt for formal occasions.",
    price: 69.99,
    category: "Clothing",
    brand: "Calvin Klein",
    rating: 4.5,
    in_stock: true,
    color: "White",
    weight: "0.3 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 13,
    name: "Dell XPS 15 Laptop",
    image: "https://picsum.photos/800/600",
    description: "Powerful laptop for professionals and gamers.",
    price: 1499.99,
    category: "Electronics",
    brand: "Dell",
    rating: 4.8,
    in_stock: true,
    color: "Silver",
    weight: "1.83 kg",
    dimensions: {
      length: "13.57 inches",
      width: "9.06 inches",
      height: "0.66 inches",
    },
  },
  {
    id: 14,
    name: "Nike Women's Running Shoes",
    image: "https://picsum.photos/800/600",
    description: "Comfortable and supportive running shoes for women.",
    price: 89.99,
    category: "Footwear",
    brand: "Nike",
    rating: 4.7,
    in_stock: true,
    color: "Pink/Gray",
    weight: "0.4 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 15,
    name: "Cuisinart 12-Cup Coffee Maker",
    image: "https://picsum.photos/800/600",
    description: "Brew delicious coffee with this 12-cup coffee maker.",
    price: 59.99,
    category: "Kitchen",
    brand: "Cuisinart",
    rating: 4.6,
    in_stock: true,
    color: "Black",
    weight: "3.18 kg",
    dimensions: {
      length: "10.13 inches",
      width: "10.38 inches",
      height: "14.25 inches",
    },
  },
  {
    id: 16,
    name: "Under Armour Men's Hoodie",
    image: "https://picsum.photos/800/600",
    description: "A comfortable and warm hoodie for men.",
    price: 49.99,
    category: "Clothing",
    brand: "Under Armour",
    rating: 4.5,
    in_stock: true,
    color: "Gray",
    weight: "0.6 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 17,
    name: "Canon EOS Rebel T7i DSLR Camera",
    image: "https://picsum.photos/800/600",
    description: "Capture stunning photos with this DSLR camera.",
    price: 699.99,
    category: "Electronics",
    brand: "Canon",
    rating: 4.7,
    in_stock: true,
    color: "Black",
    weight: "0.53 kg",
    dimensions: {
      length: "5.16 inches",
      width: "3.94 inches",
      height: "3.03 inches",
    },
  },
  {
    id: 18,
    name: "Puma Men's Running Shoes",
    image: "https://picsum.photos/800/600",
    description: "Durable and comfortable running shoes for men.",
    price: 69.99,
    category: "Footwear",
    brand: "Puma",
    rating: 4.6,
    in_stock: true,
    color: "Black/White",
    weight: "0.4 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 19,
    name: "Amazon Echo Dot (4th Gen) Smart Speaker",
    image: "https://picsum.photos/800/600",
    description: "Voice-controlled smart speaker for your home.",
    price: 49.99,
    category: "Electronics",
    brand: "Amazon",
    rating: 4.6,
    in_stock: true,
    color: "Charcoal",
    weight: "0.34 kg",
    dimensions: {
      length: "3.89 inches",
      width: "3.89 inches",
      height: "3.50 inches",
    },
  },
  {
    id: 20,
    name: "Nike Women's Yoga Leggings",
    image: "https://picsum.photos/800/600",
    description: "Comfortable and stretchy leggings for yoga and workouts.",
    price: 34.99,
    category: "Clothing",
    brand: "Nike",
    rating: 4.7,
    in_stock: true,
    color: "Black",
    weight: "0.2 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
];
